// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNGa0_OWVFpqznRvV3G_cIq-lPtGhnCBQ',
    appId: '1:849761150816:web:088d88b0702a7796892005',
    messagingSenderId: '849761150816',
    projectId: 'women-safety-app-90f74',
    authDomain: 'women-safety-app-90f74.firebaseapp.com',
    storageBucket: 'women-safety-app-90f74.appspot.com',
    measurementId: 'G-PJQLBSXYPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeSL8-wX-ql0Q35ToTm-V-ADcbMRaVNAc',
    appId: '1:849761150816:android:c7566e5afd52701d892005',
    messagingSenderId: '849761150816',
    projectId: 'women-safety-app-90f74',
    storageBucket: 'women-safety-app-90f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YQPEvI_8ZgfwpbYF69-Cl6qh6BYgS6I',
    appId: '1:849761150816:ios:d00d1b62e3ac2ed9892005',
    messagingSenderId: '849761150816',
    projectId: 'women-safety-app-90f74',
    storageBucket: 'women-safety-app-90f74.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7YQPEvI_8ZgfwpbYF69-Cl6qh6BYgS6I',
    appId: '1:849761150816:ios:d00d1b62e3ac2ed9892005',
    messagingSenderId: '849761150816',
    projectId: 'women-safety-app-90f74',
    storageBucket: 'women-safety-app-90f74.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNGa0_OWVFpqznRvV3G_cIq-lPtGhnCBQ',
    appId: '1:849761150816:web:b582fd51927c6d37892005',
    messagingSenderId: '849761150816',
    projectId: 'women-safety-app-90f74',
    authDomain: 'women-safety-app-90f74.firebaseapp.com',
    storageBucket: 'women-safety-app-90f74.appspot.com',
    measurementId: 'G-SKQV8Y0QD8',
  );

}